language: node_js

deploy:
  provider: npm
  before_script: "npm run ghpages"
  script: "release.sh"
  skip_cleanup: true
  email: garethdn@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: garethdn/TravisCITesting
    branch: master

notifications:
  email:
    recipients:
    - gareth.nolan@newswhip.com
    on_success: change
    on_failure: always

